spring:
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: debug

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
